unified_metric:
  class_path: comet.models.UnifiedMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    encoder_model: XLM-RoBERTa
    pretrained_model: microsoft/infoxlm-large
    sent_layer: mix
    layer_norm: False
    layer_transformation: sparsemax
    layerwise_decay: 0.95
    loss: mse
    dropout: 0.1
    batch_size: 4
    activations: Tanh
    input_segments:
      - mt
      - src
      - ref
    train_data:
      - data/wmt-human-eval/metric_dataset.csv
    validation_data: 0.1
    hidden_sizes:
    - 3072
    - 1024
    word_level_training: False
    min_zscore: -1.9820798505893629
    max_zscore: 0.8901959611657179
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_ckpt/mm+ptm.infolm-l+p.1.yaml